{% set version = "0.11.1" %}

package:
  name: tpot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/T/TPOT/TPOT-{{ version }}.tar.gz
  sha256: 0524a7b9102e188b0035ad1d9de3ecb1b6e6c7a47ce6d5e8fdae37bd9194156c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - tpot=tpot:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - deap >=1.2
    - joblib >=0.13.2
    - numpy >=1.16.3
    - pandas >=0.24.2
    - python >=3.5
    - scikit-learn >=0.21.0
    - scipy >=1.3.1
    - stopit >=1.1.1
    - tqdm >=4.36.1
    - update_checker >=0.16

test:
  requires:
    - dask >=0.18.2
    - dask-ml >=1.0.0
    - distributed >=1.22.1
    - nose
    - py-xgboost
    - python
    - scikit-mdr >=0.4.4
    - skrebate >=0.3.4
  source_files:
    - tests
  imports:
    - tpot
  commands:
    - tpot --help
    - tpot --version
    - nosetests tests

about:
  home: https://epistasislab.github.io/tpot/
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python tool that automatically creates and optimizes Machine Learning pipelines using genetic programming.'
  dev_url: https://github.com/EpistasisLab/tpot
  description: |
    Consider TPOT your Data Science Assistant. TPOT is a Python Automated
    Machine Learning tool that optimizes machine learning pipelines using
    genetic programming.

    TPOT will automate the most tedious part of machine learning by
    intelligently exploring thousands of possible pipelines to find the best
    one for your data.

    Once TPOT is finished searching (or you get tired of waiting), it provides
    you with the Python code for the best pipeline it found so you can tinker
    with the pipeline from there.

    TPOT is built on top of scikit-learn, so all of the code it generates
    should look familiar... if you're familiar with scikit-learn, anyway.

    TPOT is still under active development and we encourage you to check back
    on this repository regularly for updates.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
