travis:
  secure:
    BINSTAR_TOKEN: HzAr67sGGn0og/9R+K9F4TPJm501lffib/j5K7uMa4vE8o6wcWLVN7Fs/0Qmd0t3N0sBe5GUWhkYiew8o4lkW9AEM7sCtoYFcv5iJWUYffrqSQvgaqg1VsnezeYh0rLuGP0gTrg/0TYqDr6vPBjY6ODjLMF5xDjXwLbLSgPN9ubodU6QB+YfVS8sTIJy+wBg05svQdhvyJXn5LbWPyDRrgDIjJpugqgQSye6zyVd4/hVLjmC9KzulJS2nlH55W8jsVt2zonq61GcSXCiqL8bBMfg9/fVki02NWztitG+97DJsW3B3xxu4aEyfnlDuUxuWsfcoyO3GNYVxU5ZyPI2Sip7J56otKRc82SkxRCpCvWHdCjiwwxbK75rJZaZIjgyAG6p209Y/7oQbZj7wUzozSzUbtHV3oZuuI3xyk3Fb7kfn856y2hCR5zmQSW2m/ypSBCt3C8J67ET65VJ9ochQ/cJ/mmS03NMU6rVdt9LSdLCvaMHYhxbam1nYrRGr2zKNsShJUg6yS+Brk2zGLUiB3XAiYchf3hlEZBm7gJhjlT6Im8nLR9dBjgNipCsBBxGNHBUYw65ngdARH64q2iioL3kf1YwKpvVm2fUNvCNOlYk1cny/BZS3KxTGSxnQ/WL5jfzuV6arnq/62mYwuC+So6kEcwpuXbeEqbW6G/mfHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
