travis:
  secure:
    BINSTAR_TOKEN: Q9Lj7h+7q8UuDucmGirePEQtAulkSCIVGnyxBzrj4TPwEVcnK0nMdNfYlEg924562W0S/0//3Doq3spf8a6uko7g5hZq41ckZhX5S3w6nPV2uWjIxaYXoZlL5xb2QICOUlOwPl0ctfF7r8gl178PQFnLa8W1Y7tzRkZRNZGP1n9Hk2YAOVvNOsw7thmUdyoeFiyLOFss7mXJzhMsgq7/od9bwv9j9tcnKKTUbUKqlqdgdUqC4etJzwARHgNvi+SjJ3vvJiUePwJa9B+X9tBXkXLBQ6wuYj4agmFyH0mryIeNl7oCSxLOiJUh4eGM82/b50Qnwy4nQy1RJzfh86Qy7vS4h+Z7E7lBsIqbWD7tOu2RBwUcxAGMKgJwRKE9+g0YgAaNsGvv8Apgyv1vsy8B0soiSAY48l5Tu1SzKr6G47p3Jbrat2zeoYWlAkzI05IMuBYC5CPRjJT9D7eAy0alPkilYWrVYNtiHPzbWCDIRWwkDXoL+Nauosk4MXsjEHuutMUfl9vFJ/4FMfwLTYTjCNOvAwdnqib2ApTcBQf3aTSeBMkXtsp+H4KRIPmd759N8yXF6BGaDg1fWXeOm9Z6poF0j+SUYqz2Fp0ykNhkUvWSqiO+ScetjlAH9gKvpDuOxLOGpkepfNsUvhgmO7SOWZQQmB/HSKKCgsAdTT30/DY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
