appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: Rm8sjCEAVLxoKB7RFW0dOms+oTdl/uNDMBqgl20ZvEeYDr/MDPd487izHQib330sSjk+TmooHCw/Botp7h2aSeQ+WI6uWnU9xO5+wh6GgEbzuF9qZsAahI8840mAjxTb85FOXImd5sEJDj9i9jpwMPuE4/4qRLwe0aPnzcs/7CV8EODsZTOVUwxjJ3DASIfZbuaJVivCGluU67xCMT92An/VCM5uzAiUcDni8oDMIZLnua6FdId8ll3HHV8JKum5bh7qY4savb9BmVosSIaBLOL7SpZrFrZI5DLT85umX7QuGDdyzGD2TstwR33e0ZB6yVabg/UEuBzFw+Hk5E9j7UwuErzoiAY7VgbJJCgSiMSNvkJOLvpbZnNsR26mha7e6tw+Z3XC4a8WRHODeWX6d9FypvyoBkbTJpMMoFXx6lLidUXkIF+vBm4msp8MP0xvuTx79pDNO1KqDmUOTLlE3iMFgwtViHZfSVhhl5l2mWwdKWzBF8aQmxFOn9sSSAhp0CzqiUVoCXoJLnOvSOBylrCLqXZioWVhDtYrKd/ISAcaYepcrdZ9P6e3mo6vFCj1TC48jY559pm72XH0YltShTrJvZkYhwZCGSf+wkdUTvkay4mSIUovxctm+zhl7ZEf66yyEGRedzRGLYwvuUnRE456ALAEApvtVs0secnYzuI=}
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
